#!/bin/bash

echo "
[client]
user=root
password=$MYSQL_ROOT_PASSWORD
" > /usr/local/mysql-repl/conf.d/self.cnf

if [ "$MYSQL_ROLE" == "master" ]; then
    exit 0
fi

echo "
[client]
user=$MYSQL_REPLICATION_USER
password=$MYSQL_REPLICATION_PASSWORD
host=$MYSQL_REPLICATION_HOST
port=$MYSQL_REPLICATION_PORT
" > /usr/local/mysql-repl/conf.d/master.cnf

exit 0
