#!/bin/bash

function client() {
    mysql --defaults-extra-file=/usr/local/mysql-repl/conf.d/self.cnf -e "$1"
}

function print_step() {
    echo "[REPLICATION] [REPLICA] $1"
}

if [ "$MYSQL_ROLE" != "replica" ]; then
  exit 0
fi

print_step "Setting up replica"

(
    print_step "Waiting for mysql database to be up"

    while ! client "SELECT 1;" &> /dev/null; do
        sleep 1
    done

    sleep 5

    print_step "Executing replica commands"

    client "
        STOP REPLICA;

        RESET REPLICA;

        CHANGE MASTER TO
            MASTER_HOST='$MYSQL_REPLICATION_HOST',
            MASTER_PORT=$MYSQL_REPLICATION_PORT,
            MASTER_USER='$MYSQL_REPLICATION_USER',
            MASTER_PASSWORD='$MYSQL_REPLICATION_PASSWORD';

        START REPLICA;
    "

    print_step "Done"
) &

exit 0
